server:
  port: 8099
spring:
  application:
    name: lk-gateway
  cloud:
    gateway:
      routes:
        - id: lk-backend
          uri: http://localhost:8091
          predicates:
            - Path=/userApi/**
          filters:
            - StripPrefix=1

        - id: lk-analyze
          uri: http://localhost:8092
          predicates:
            - Path=/analyzeApi/**
          filters:
            - StripPrefix=1
  redis:
    host: localhost
    port: 6379
    database: 1

dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
    parameters.register-consumer-url: true