server:
  port: 8091
spring:
  application:
    name: lk-backend
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/chartbi?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 86912148k
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  session:
    store-type: redis
    timeout: 2592000

  redis:
    database: 4
    host: localhost
    port: 6379
    timeout: 5000

  rabbitmq:
    addresses: localhost
    port: 5672
    password: guest
    username: guest
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000
          multiplier: 1.5
          max-interval: 60000

dubbo:
  application:
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


alipay:
  appId: 9021000130614767
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCkYV813dsBW0dgy97DRKuksXNF0nm5OeHZaJvdoOWPS6LWAM1HcfkLys8ie4eYjYSK7ZWtf62/vqgILtZ9kvjEydy5qSQQgSMTVq7Dib9SQ3aprozQShvbrk9bpYFDvYjwEDzOnx58sSsqnFgQTzXjdgOt5EWEY8fghiKRUt8utjl9XjkNSg7AILbS57goI/h34ggQQFxI6dz0MHl7/VowO3+HT4q2fetytbX7coX/BJIfGl+U6xfb6oRZ1J6aoFLGlDfLrvcCKf1Id04JB5nyDkppVJQPspdNJ9wKD2R+G/7JU2NJEhO2mlpnh5h/qj4RAd2Im+MroLzAuBHGJLzRAgMBAAECggEASqlrfGT7X19dSUrwMFMVfyWWTQVvgkEXIw+PlBfLjM129arBkozi6IdCk8/148WLiSqmjHpsqaXoXmcfx0OlOITTe4Smu9Rb4SHDGU+MlcnMsP92N/khNCO1KdQ/pUwGUbueUt8VEt/J0n3WxfmkaV8mBqqjJKHJnGJwev9gHa+tfDUofukmruzVfmxogcBdZPauwqLCSpXRv05OO3JbpznAiqyh+h7TOm6DuIQViHiBUupkxbiHyklQx7zNp+GpRAuGNtvXSKslJ8LTKjeoYydvlO0MfLUxGcxXAIuXMSOsfX5mQt1JUEH7acXGooUE6ByvROUaxNy5MWgJIWrBkQKBgQDkTB7adsX++UjDfoZ9dfYriHuzTk5pDo/XxalnFkbkaUMWAt2JYMXWFPLv0mfxWEv3LR4YjO/tkIAHsZtMWlhR8hRG5Oj8ecx0e/WWeUZZ6X8PYqJ1QXaDPVkVgCVe5Br3YEN2H3mARqfdv5lpigbBpFHzoinyQeOagMklFLm91QKBgQC4U7hMZek2EovIv4eWIZYIZvd16r1aM/GPa0uxI/58OxyRsYjIBpUYW10VuEcz2h+t9xIQdCsJqJ+MlYfjgFl4BZLrVXlF21gkw1Jqvq2/mcqXRtAa/T7o0gVGuYCNW17VbwF/XMVJVXtpkwwz9laUfJEG/355bod1vRj7skU1DQKBgBmijohbc+oolcoV6AYoe8bxoWpF7boQP4isElSYBMfbJgRPuA6YBj7+xTS2vKM2FfmgYFPDZ6GWaznx8I1HS8mP1EUNqTfIeXPPA4ms/oBUHsdcfP+LpUIhXmJyrD+Wf4yti4W1DRChXnIg9JoMPKv7xpQD7o/cZDFSKsP2KtEtAoGBAIUK8IA8IpsDwd8w1yV2snr4Du8OcoOT8GvrLuP5repvJAzIzohJr/23nDVcIBB+BNWk+mXj41iCXD61gzKi5nDp3QR9Wh4g1rsaO/eOD4y27XJJC1YfqfOT+3jz1aSx6X42NCeAh2mKCJzIJUuwJwff7THW4au2KpHB3jF1l9xVAoGBAND01ibGR4hieSdUptxqfsXlS+uUc1KdgthRsbUMgDVLH5G3rlxU/U1qXzQSQFXRYSOtWtlgKlKmih1XFHf8F5HtmWZFwCsLncRrxEP/HgmsJrBmWkefVXCPlLy6WVPPmDtNpi38xtSrALApJOieYBcJfTO3tTIvjtfJOopmOYgR
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn9o33ucRapGreyCj7RQthPJZWRW107UpjhMDOZ1z9z3UfoECNl8FWKrd4vRHpGIz0WQR3XwgonHnp0q9deo89cai+ReTEClDKczuzHJQ16CuoKcC4J23IU0qPdmva3C0btV9iKdh5RRvZRomCgGTVv5D045ZhkFaCLqw9RMSyUDu+3TxBtijAbra7NUKDhw+yge7vv23Nd2WCnxktq1KDpY3lCT+EBIRslNTbdgrdIiFaQ204VL9Agita2zW04iCHC7FeYJw2FJuTWmwfx7mJabD+4bTATYmeqlIsnG08Yn/3hrxfKRml7+uZULkE/2d44aoyT1GriQvyEtYb34zNQIDAQAB

cloud:
  oss:
    endpoint: http://127.0.0.1:9000
    bucket: chart
    access-key: minioadmin
    secret-key: minioadmin