server:
  port: 8091
spring:
  application:
    name: lk-backend
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/chartbi?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 86912148k
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  session:
    store-type: redis
    timeout: 2592000

  redis:
    database: 4
    host: localhost
    port: 6379
    timeout: 5000

  rabbitmq:
    addresses: localhost
    port: 5672
    password: guest
    username: guest
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000
          multiplier: 1.5
          max-interval: 60000

dubbo:
  application:
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


alipay:
  appId: 9021000122698871
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCBHgcsrfkv0Nr53utTVrahPROCYrubDm5pplOuP++h3PnDdUNWw+h6l3kB8X6Kl8/tt2OESWC97z8/TnBm7dG/LDVMQ+qLsjBATsRXYzhe/HwYdHxy+x2n3Hn1mVcTdP30U4WspRPBtD/cTQk8Ad/q3DWXbWiX6GWcRB9J+OrB2bu55thxRkFfUsfsYLempc4ClrTgt142nkyTJWf9ZWIFezNkLFRsMH/Gas+vN4Y9dx7mnQIvqS0tdJta6Uc9KBxDggN3qtOhkbh2HxVDzCUVp0cuuTV6jeji7V5f9QEV5NSex3J6yMc2OA9XatkuKeH9lSCXaPSOK7uVpT0/pzIJAgMBAAECggEAQPcp5vo2Si/NLjJSt6EGzUQc39rryE3PkksFCcTTvt6fsQ/8bNivzZcPZMHsyLEwBsziPrpo+cg6S5EdDz0T7xvASXpWtilXC9RWCB49S9XAXtGlmHjvZ/mQR9n6rSiNavTnaoG42hrmkuMUBWRwFQztzh5XpS9iiOjh0Wd0P0qmi8R74LKjposd/fV/PvX+Y3aVznI2MxDXg4ZYEEk2kp6Str7sed6SY1l47u7Ok4ACVqVrdjozveQ6CRdpiYZ+InoEQ3sOcJsypJ9H/vTiKHMhT14I/K9D3be/R/zFjaeteH7y5VMLLnkFFdnXhMw1SyT6669FIvfooeBlaJQB/QKBgQC8toZtGfZ+zl2Z5260NhZaO8bBklCfpmsW4cowxLF3bdtjSSu9umgKLGT/VHfMrlh5g6Kp4T6t5DGBISGHS53PqNmAlR9QzXXpg4p1z5gWKE7G7+JCxzXFZUKz7Hj3AhhA7DH+4oZ5rzyHQN25tMH8LLP+x6JiF0W5xLrxlNYG2wKBgQCvJ6+j72y7BMxPC2Ke7DMGjIo9gFnt/vALJ2qTNK/bcHbZruAsq6hFJIwSqrLzM0n7oDPRJbMEElX90xLzEvoqYBLzRcxcHWQFqnNr6RVId6BMnVduNioS4o5IWqgVxAsYV7mMb4pGH+vMak/P4tXxqwHUzPyzSVeW7jLhtjfl6wKBgQCjRFcw9RFpzCj3Cl+g0lqsXqMqvee6+EQWW+qOHt5bMVRppdiOIUP56UbIENBE6WHqX5TP3OxZjd+2lG9pmmZCTxc+Q8YAJoIpMYENRDmUkfL18nySwb8ntN/swl41dj59jNwEZP9rL8zyR5CNJnHeNt7TQuyeaPwOKMKEV/yDmQKBgHGaIdcH0NOzlvelgL9mnumeeYLOHoW4FeSGGh+DypNe7Bbfz1Hpu+esfpUU1Z/bIh7rlvANrX/0jIVmQyIYqtyVF3VlTdhoz5jFJrtUn5My02sdmblHtB4vhuzyr5X+YtvU+elV5q74wS0BvuYsT2rA6R0mHrgB16dystmmH7clAoGAFDfjBgb2NvjS41fFbBPj32UHwXN4W9R9Nb2E+ERwhr36ztzfIHA871Za497/+jUXOMmsu44Iz3la6wZMKWCweSUJfqeZ7Vfz5gchjHPO17159S0WRd2vpS32QEtzPr8FYYDBpGGQVuwD/VM9E4w16qq10SeMMwZxRsr7rAMuXdc=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtArMSQwGm+etlaXghRdcgodQc8AaVRbN9oReCP1VID8145qeP238rRFr55kUdnUnUGUlb4bDAsUIZfNHexGM4hceEtv3AETBkm7r/5o5VFi86zWF536rg2GDqDbNIu0apTXIqpSYAqZRlwTCuz0BXrWWe/dd4O0KF/WLLh5Doyrghcu0oVzd6UahZ5IJdOzpmAXuSW+8fNxaddyBtFoIfa+NFc/xbqcCwhjaP4bT8NCfBeYmhYraqdVgM2ljINs8jS+DZkmLnbDvBlIQwt/8irKoSN2aCYc/GzCSPxh7L/dWiGppekQU55K5T6pU9cQDRSKzWMgqxlpF2ak3MjcLxQIDAQAB


yuapi:
  client:
    access-key: vlo57mujjl82rtjwo97hxt708uonsbaf
    secret-key: ij995szshxp0xfvc8z0nasnfopeqb1nv